# Generated by Django 3.2.4 on 2021-06-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0003_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
